.

diff --git a/.github/workflows/build-cmd.yml b/.github/workflows/build-cmd.yml
--- a/.github/workflows/build-cmd.yml
+++ b/.github/workflows/build-cmd.yml
@@ -49,7 +49,13 @@ jobs:
             REF="refs/pull/${{ inputs.number }}/merge"
             BASE_TAG="pr-${{inputs.number}}-"
           elif [[ "${{ inputs.origin }}" == "issue" ]]; then
-            BRANCH=$(printf "%s" "${{ inputs.args }}" | jq -r '.[0]')
+            BRANCH=$(printf "%s" "${{ inputs.args }}" | jq -r ".[0]")
+
+            if [[ "$BRANCH" == "" ]]; then
+              echo "##[error]Missing argument branch at index 0 in command."
+              exit 1
+            fi
+
             REF="refs/head/${BRANCH}"
             BASE_TAG="ci-${BRANCH}-"
           fi
@@ -70,7 +76,7 @@ jobs:
           set -euo pipefail
 
           if [ -z "$COUNT" ] || [ "$COUNT" -lt 0 ] && [ "$COUNT" -ne -1 ]; then
-            echo "❌ Invalid count: $COUNT. May only be > 0."
+            echo "##[error]Invalid count: $COUNT. May only be > 0."
             exit 1
           fi
 
@@ -105,13 +111,13 @@ jobs:
           FINAL_TAG=${PREFIX}${COUNT}
 
           if echo "$TAGS" | grep -qx "$FINAL_TAG"; then
-            echo "⚠️ Tag $FINAL_TAG already exists."
+            echo "##[warn]Tag $FINAL_TAG already exists."
 
             if [ "${GITHUB_ACTOR}" != "${{ github.repository_owner }}" ]; then
-              echo "🚨 User $GITHUB_ACTOR is not allowed to overwrite existing image."
+              echo "##[error]User $GITHUB_ACTOR is not allowed to overwrite existing image."
               exit 1
             else
-              echo "User $GITHUB_ACTOR is the owner - allowed to proceed."
+              echo "User $GITHUB_ACTOR is the owner – allowed to proceed."
             fi
           fi
 
