.

diff --git a/.github/workflows/build-cmd.yml b/.github/workflows/build-cmd.yml
--- a/.github/workflows/build-cmd.yml
+++ b/.github/workflows/build-cmd.yml
@@ -52,8 +52,7 @@ jobs:
             BRANCH=$(printf "%s" "${{ inputs.args }}" | jq -r ".[0]")
 
             if [[ -z "$BRANCH" || "$BRANCH" == "null" ]]; then
-                echo "::error::Missing argument branch at index 0 in command."
-              exit 1
+              echo "::error::Missing argument branch at index 0 in command." && exit 1
             fi
 
             REF="refs/head/${BRANCH}"
@@ -76,8 +75,7 @@ jobs:
           set -euo pipefail
 
           if [ -z "$COUNT" ] || [ "$COUNT" -lt 0 ] && [ "$COUNT" -ne -1 ]; then
-            echo "::error::Invalid count: $COUNT. May only be > 0."
-            exit 1
+            echo "::error::Invalid count: $COUNT. May only be > 0." && exit 1
           fi
 
           PREFIX="${{ env.BASE_TAG }}"
@@ -114,8 +112,7 @@ jobs:
             echo "::warn::Tag $FINAL_TAG already exists."
 
             if [ "${GITHUB_ACTOR}" != "${{ github.repository_owner }}" ]; then
-              echo "::error::User $GITHUB_ACTOR is not allowed to overwrite existing image."
-              exit 1
+              echo "::error::User $GITHUB_ACTOR is not allowed to overwrite existing image." && exit 1
             else
               echo "User $GITHUB_ACTOR is the owner – allowed to proceed."
             fi
